### PR TITLE
75 genre select

### LINKED ISSUE #75: Implement Genre Select Functionality
## Expected Behaviour

Users want to find movies based on the genre. Right now, there is a front-end implementation on the homepage for choosing genres. But if you click on a genre icon, it doesn't yet filter movies from that genre.

Please implement the genre select functionality on the homepage.

## Checklist

- [x] Create a new branch to implement this new feature
- [x] Implement an onClick function for the genre icons
- [x] Make use of the function getMoviesByGenre in src/services/tmdb.ts
- [x] Show the results of the API call on the homepage

### PR DESCRIPTION
**Pull request by nakropin**
## Checklist

Confirm you have completed the following actions prior to submitting this PR.

- [ x ] There is an existing issue report for this PR.
- [ x ] I have created a feature branch.
- [ x ] My changes have been committed.
- [ x ] I have pushed my changes to the branch.

## Description

It is now possible to select genres to filter movies in the overview. Slight modification to some other components have been done so that you can navigate to  the GenreOverview page

Closes #75

### CODE REVIEW

**Comment by louziferr** [comment]
Please push routes/genreoverviewpage.tsx

**Comment by louziferr** [comment]
Please implement functionality to choose from one of many genres in the genre overview page.

**Comment by nakropin** [comment]
> Please implement functionality to choose from one of many genres in the genre overview page.

done, see last commit

**Review by louziferr — APPROVED** [review]
all done! Nice

**Pull request merged**
